### ISSUE TITLE
Gracefully reset the game if the server shuts down

### ISSUE THREAD

**Issue by wearhere** [wearhere/spacecontrol#15]
What the panels should do is periodically try to reconnect until the server comes back up, at which point the server should re-enter the ["waiting for game" mode](https://github.com/wearhere/spacecontrol/issues/9).

(Would it be nice for the game to jump back to the level at which the players left off? Probably, but that'd be harder and might be over-optimizing for an error state.)

What the panels currently do is crash with this error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jeffreywear/Dropbox/Development/spacecontrol/panels/panel_client.py", line 100, in _server_io_subprocess_main
    messenger.send(action)
  File "/Users/jeffreywear/Dropbox/Development/spacecontrol/panels/panel_client.py", line 182, in send
    self._socket.sendall(_encode(message))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe
```

**Comment by wearhere** [comment]
@igor47 for https://github.com/wearhere/spacecontrol/issues/35, can we restart after a short delay? If so, then we could punt reconnect logic in favor of just restarting the process. (Note to self: also requires https://github.com/wearhere/spacecontrol/issues/36.)

(We could also do this without a delay between restarts, it would just burn unnecessary CPU.)

**Comment by wearhere** [comment]
@igor47 assigning to you pending my previous question
